apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: controller
  newName: risingwave-resource-operator
  newTag: dev
commonLabels:
  app.kubernetes.io/component: manager
  app.kubernetes.io/name: risingwave-resource-operator
