---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - risingwave.risingwavelabs.com
  resources:
  - risingwavedatabases
  - risingwaveschemas
  - risingwaveusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - risingwave.risingwavelabs.com
  resources:
  - risingwavedatabases/finalizers
  - risingwaveschemas/finalizers
  - risingwaveusers/finalizers
  verbs:
  - update
- apiGroups:
  - risingwave.risingwavelabs.com
  resources:
  - risingwavedatabases/status
  - risingwaveschemas/status
  - risingwaveusers/status
  verbs:
  - get
  - patch
  - update
