apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- risingwave_v1alpha1_risingwaveuser.yaml
- risingwave_v1alpha1_risingwavedatabase.yaml
- risingwave_v1alpha1_risingwaveschema.yaml
commonLabels:
  app.kubernetes.io/name: risingwave-resource-operator
  app.kubernetes.io/component: sample
