apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: risingwaveusers.risingwave.risingwavelabs.com
spec:
  names:
    plural: risingwaveusers
    singular: risingwaveuser
    kind: RisingWaveUser
    shortNames:
    - rwu
  group: risingwave.risingwavelabs.com
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
